name: pgray
services:
  pgray-postgres:
    container_name: pgray-postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - pgray-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  pgray-postgres-data:
    name: pgray-postgres-data